### ISSUE TITLE
For each subsequent build, the pkgver gets longer and longer

### ISSUE THREAD

**Issue by joejulian** [troywill/zoneminder-aur#12]
Due to the way that makepkg updates the pkgver string in the PKGBUILD each subsequent build appends the pkgver to the previous pkgver.

**Comment by troywill** [comment]
Thanks for your help with this. I simplified the pkgver function you came up with with the documentation at  https://wiki.archlinux.org/index.php/VCS_package_guidelines#The_pkgver.28.29_function.

**Comment by joejulian** [comment]
Thanks for the link. I hadn't seen that.
