### ISSUE TITLE
Installation fails to chmod rules.d

### ISSUE THREAD

**Issue by joejulian** [troywill/zoneminder-aur#16]
POLKIT_PREFIX is not initializing correctly causing the polkit tree to be installed to root. This, of course, causes the chmods to fail. Define the POLKIT_PREFIX.

**Comment by troywill** [comment]
I don't think POLKIT_PREFIX is used anywhere. I'm guessing you grepped POLKIT_PREFIX in a couple of the config files from the old build system, e.g. zoneminder/configure.ac, and you inferred that it needs to be defined. However, I can't see that it does anything with the CMAKE build system that Zoneminder uses now.

I found that deleting the src directory before running makepkg solves the problem.

Thanks for your input.

**Comment by joejulian** [comment]
Even better. Not sure why it worked for me then, but it seemed a little hacky. Glad you got it figured out.
