### ISSUE TITLE
Fix For Install Warnings

### ISSUE THREAD

**Issue by cspenceiv** [troywill/zoneminder-aur#7]
I noticed that while installing the package with pacman, a couple warnings appear:

<i>warning: directory permissions differ on /usr/share/polkit-1/rules.d/
filesystem: 700  package: 755
warning: directory ownership differs on /usr/share/polkit-1/rules.d/
filesystem: 102:0  package: 0:0</i>

These warnings can be fixed by including these three lines on the end of the package() section:

<code># Fixing permissions</code>
<code>chmod 700 $pkgdir/usr/share/polkit-1/rules.d/</code>
<code>chown polkitd $pkgdir/usr/share/polkit-1/rules.d/</code>

**Comment by troywill** [comment]
Thanks. zoneminder PKGBUILD updated and uploaded to AUR as zoneminder 1.28.0-9. zoneminder-git PKGBUILD updated to.
